### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by Ringwid** [Grace5921/android_device_samsung_a8eltezh#1]
Could you please update this device tree to CM14 if possible?
Thanks

**Comment by Grace5921** [comment]
it would be better to make los14.1 (7.1.2 ) and yes it's easy to update

**Comment by Ringwid** [comment]
Great, but does the prebuilt kernel need update? Samsung has provided the kernel source, are there any parameters need changing?

**Comment by Grace5921** [comment]
can we talk on hangouts ?
